# development:
#   DATABASE_URL: postgres:///35mm_dev
# test:
#   DATABASE_URL: postgres:///35mm_test
# production:
#   DATABASE_URL: <%=ThirtyFiveMilimeters::Config.database_url%>



development:
  adapter: postgresql
  name: 35mm_dev
test:
  adapter: postgresql
  name: 35mm_test
production:
  DATABASE_URL: <%=ThirtyFiveMilimeters::Config.database_url%>

